### ISSUE TITLE
Cannot require "inspec-objects" gem

### ISSUE THREAD

**Issue by lukemalinowski** [inspec/inspec-objects#2]
Attempting to require the "inspec-objects" gem returns error: `LoadError (cannot load such file -- inspec-objects)`

# Describe the problem
Attempting to import the inspec-objects gem returns an error. It may be the case that there is a different import statement than what I am expecting. If so, it would be useful to have it in the README.
The tests `require "inspec/objects"` and since objects still exist in inspec it is unclear to me if that require statement will pull in the inspec-objects version of objects or the inspec version of objects. Which will be a valid import until the April release according to the issue deprecating inspec/objects.

```
2.6.0 :001 > require "inspec-objects"
Traceback (most recent call last):
       16: from /Users/username/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
       15: from /Users/username/.rvm/gems/ruby-2.6.3/bin/bundle:23:in `<main>'
       14: from /Users/username/.rvm/gems/ruby-2.6.3/bin/bundle:23:in `load'
       13: from /Users/username/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
       12: from /Users/username/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
       11: from /Users/username/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
       10: from /Users/username/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:18:in `start'
        9: from /Users/username/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
        8: from /Users/username/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
        7: from /Users/username/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
        6: from /Users/username/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        5: from /Users/username/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        4: from /Users/username/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:494:in `console'
        3: from /Users/username/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/cli/console.rb:19:in `run'
        2: from (irb):1
        1: from (irb):1:in `require'
LoadError (cannot load such file -- inspec-objects)
```

## Possible Solution
Add a statement to the README explaining how to appropriately depend on the deprecated objects library, or add lib/inspec-objects.rb to make gem importable.

**Comment by clintoncwolfe** [comment]
As this repo is being archived, all issues and PRs are being closed. Thank you for your interest!
